version: '3.8'
services:
  web:
    build: .
    ports:
      - "8090:8000"
    volumes:
      - .:/code
      - static_volume:/code/static
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  static_volume:
