---
- name: Deploy application to Kubernetes
  hosts: localhost
  tasks:
    - name: Apply Kubernetes deployment
      community.kubernetes.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        src: "./../k8s/deployment.yaml"

    - name: Apply Kubernetes service
      community.kubernetes.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        src: "./../k8s/service.yaml"
